// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function SetAutoMode(arg1) {
  return window['go']['main']['App']['SetAutoMode'](arg1);
}

export function SetStartAtLogin(arg1) {
  return window['go']['main']['App']['SetStartAtLogin'](arg1);
}

export function SetStartProxyOnLaunch(arg1) {
  return window['go']['main']['App']['SetStartProxyOnLaunch'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestConnections(arg1) {
  return window['go']['main']['App']['TestConnections'](arg1);
}

export function TestProxy() {
  return window['go']['main']['App']['TestProxy']();
}
