// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestConnections(arg1) {
  return window['go']['main']['App']['TestConnections'](arg1);
}
